Amelioration des tools admin, renforcement de la configuration de portsentry

diff --git a/admin_tools/files/pg_tools b/admin_tools/files/pg_tools
--- a/admin_tools/files/pg_tools
+++ b/admin_tools/files/pg_tools
@@ -4,9 +4,7 @@
 # 1°) Copy file into this directory :
 # 	cp pg_tools /usr/local/bin/pg_tools
 # 	chmod 755 /usr/local/bin/pg_tools
-
 # You can call command pg_tools in your shell as user root
-
 ######### ===== END =====
 
 RED='\033[0;31m'
@@ -25,19 +23,24 @@ checkRoot() {
 find_pg_user() {
 	[ $# -eq 0 ] && echo "User name is mandatory!" && exit 1
 	username=$1
-  	shift;
-	local myresult=$(sudo -u postgres psql -X -P t -P format=unaligned -c "SELECT count(*) FROM pg_user WHERE usename='$username'")
-	echo "$myresult"
+  shift;
+	local result=$(sudo -u postgres psql -X -P t -P format=unaligned -c "SELECT count(*) FROM pg_user WHERE usename='$username'")
+	echo "$result"
+}
+
+list_pg_users() {
+  local result=$(sudo -u postgres psql -X -P t -P format=unaligned -c "SELECT usename FROM pg_user")
+  echo "$result"
+  pause
 }
 
 add_pg_user() {
+	echo "#################################"
+	echo "Starting  Add Postgres user"
+	echo "#################################"
 
-	echo "###################################################################################"
-	echo "Starting  Add Postgres user......."
-	echo "###################################################################################"
-
-	declare shouldMakePause=0
-
+  declare pg_right="CREATEDB"
+  declare request
 	if ! [ $# -eq 3 ] ; then
 		read -p "Enter postgres username : " username
 		read -s -p "Enter password : " password
@@ -45,21 +48,16 @@ add_pg_user() {
 		read -p "Give super-user right to this user ($YES/$NO) ? : " superuser
 	else
 		username=$1
-  		password=$2
-  		superuser=$3
-  		shift; shift; shift;
-  		shouldMakePause=1
-  	fi
+  	password=$2
+  	superuser=$3
+  	shift; shift; shift;
+  fi
 
-  	declare pg_right="CREATEDB"
-  	declare request
-
-  	if test "$superuser" = "yes"; then
+  if test "$superuser" = "$YES"; then
 		pg_right="$pg_right SUPERUSER"
 	fi
 
 	finduser=$(sudo -u postgres psql -X -P t -P format=unaligned -c "SELECT count(*) FROM pg_user WHERE usename='$username'")
-
 
 	if [ $finduser -ge 1 ] ; then
 		sudo -u postgres psql -c "ALTER ROLE $username $pg_right;"
@@ -73,68 +71,66 @@ add_pg_user() {
 	else
 		echo -e "${RED}Failed to add/update Postgres user $username. Exit !${NO_COLOR}"
 	fi
-
-	if [ $shouldMakePause -eq 1 ] ; then
-		pause
-	fi
+  pause
 }
 
 
 drop_pg_user() {
 
-	echo "###################################################################################"
-	echo "Starting  Drop Postgres user......."
-	echo "###################################################################################"
+	echo "#################################"
+	echo "Starting  Drop Postgres user"
+	echo "#################################"
 
-	declare shouldMakePause=0
+	declare makePause=0
 
 	if ! [ $# -eq 1 ] ; then
 		read -p "Enter postgres username : " username
-		shouldMakePause=1
+		makePause=1
 	else
 		username=$1
-  		shift;
-  	fi
+  	shift;
+  fi
 
-	# Drop all schema belong to user
- 	findschemas=$(sudo -u postgres psql -X -P t -P format=unaligned -c "SELECT schema_name FROM information_schema.schemata where schema_owner='$username'")
+  sudo -u postgres psql -c "DROP OWNED BY $username CASCADE;"
+  sudo -u postgres psql -c "DROP DATABASE $username;"
+  sudo -u postgres psql -c "DROP USER $username;"
 
-	echo $findschemas
+  if [ $? -eq 0 ]; then
+    echo -e "${GREEN}User $username have been dropped successfully !${NO_COLOR}"
+  else
+    echo -e "${RED}Failed to drop user $username !${NO_COLOR}"
+  fi
 
-	# TODO Drop all databases belong to user
-	# TODO Drop user
-
-	if [ $shouldMakePause -eq 1 ] ; then
+	if [ $makePause -eq 1 ] ; then
 		pause
 	fi
 }
 
-
 find_pg_database() {
 	[ $# -eq 0 ] && echo "Database name is mandatory!" && exit 1
 	database=$1
-  	shift;
-	local myresult=$(sudo -u postgres psql -X -P t -P format=unaligned -c "SELECT count(*) FROM pg_database WHERE datname='$database'")
-	echo "$myresult"
+  shift;
+	local result=$(sudo -u postgres psql -X -P t -P format=unaligned -c "SELECT count(*) FROM pg_database WHERE datname='$database'")
+	echo "$result"
 }
 
-
 add_pg_database() {
-	declare shouldMakePause=0
+	declare makePause=0
 	if ! [ $# -eq 2 ] ; then
 		read -p "Enter database name : " database
 		read -p "Enter database owner name : " owner
-		shouldMakePause=1;
+		makePause=1;
 	else
 		database=$1
-  		owner=$2
-  		shift; shift;
-  	fi
-	echo "########   Starting  add Postgres database $database with owner=$owner.  ########"
+  	owner=$2
+  	shift; shift;
+  fi
 
-	finduser=$(find_pg_user $owner)
+  echo "#####  Starting  add Postgres database $database with owner=$owner.  ######"
 
-	if [ $finduser -eq 0 ] ; then
+  finduser=$(find_pg_user $owner)
+
+  if [ $finduser -eq 0 ] ; then
 		echo "Unknown user $owner. Creating user $owner with password $owner."
 		add_pg_user $owner $owner $NO
 	fi
@@ -153,7 +149,7 @@ add_pg_database() {
 		echo -e "${RED}Failed to add/update database $database !${NO_COLOR}"
 	fi
 
-	if [ $shouldMakePause -eq 1 ] ; then
+	if [ $makePause -eq 1 ] ; then
 		pause
 	fi
 }
@@ -163,20 +159,20 @@ drop_pg_database() {
 		read -p "Enter database name : " database
 	else
 		database=$1
-  		shift;
-  	fi
-	echo "########   Starting Drop Postgres database $database.  ########"
+  	shift;
+  fi
 
-  	sudo -u postgres psql -c "DROP DATABASE $database;"
+  echo "#####  Starting Drop Postgres database $database.  #####"
 
-	if [ $? -eq 0 ]; then
+  sudo -u postgres psql -c "DROP DATABASE $database;"
+
+  if [ $? -eq 0 ]; then
 		echo -e "${GREEN}Database $database has been dropped successfully !${NO_COLOR}"
 	else
 		echo -e "${RED}Failed to drop database $database !${NO_COLOR}"
 	fi
 	pause
 }
-
 
 add_pg_schema() {
 	if ! [ $# -eq 2 ] ; then
@@ -185,19 +181,20 @@ add_pg_schema() {
 		read -p "Enter schema owner : " owner
 	else
 		database=$1
-  		schema=$2
-  		owner=$3
-  		shift; shift; shift;
-  	fi
-	echo "########   Starting  add Postgres schema $schema in database=$database.  ########"
+  	schema=$2
+  	owner=$3
+  	shift; shift; shift;
+  fi
 
-  	finddatabase=$(find_pg_database $database)
+  echo "########   Starting  add Postgres schema $schema in database=$database.  ########"
 
-	if [ $finddatabase -eq 0 ] ; then
+  finddatabase=$(find_pg_database $database)
+
+  if [ $finddatabase -eq 0 ] ; then
 		add_pg_database $database $owner
 	fi
 
-  	sudo -u postgres psql -d $database -c "SET SEARCH_PATH TO $database; CREATE SCHEMA $schema AUTHORIZATION $owner;"
+  sudo -u postgres psql -d $database -c "SET SEARCH_PATH TO $database; CREATE SCHEMA $schema AUTHORIZATION $owner;"
 
 	if [ $? -eq 0 ]; then
 		echo -e "${GREEN}Schema $schema in database=$database/owner=$owner has been added successfully !${NO_COLOR}"
@@ -214,20 +211,20 @@ drop_pg_schema() {
 	else
 		schema=$1
 		database=$2
-  		shift; shift;
-  	fi
-	echo "########   Starting Drop Postgres schema $schema.  ########"
+  	shift; shift;
+  fi
 
-  	sudo -u postgres psql -d $database -c "SET SEARCH_PATH TO $database; DROP SCHEMA $schema CASCADE;"
+  echo "########   Starting Drop Postgres schema $schema.  ########"
 
-	if [ $? -eq 0 ]; then
+  sudo -u postgres psql -d $database -c "SET SEARCH_PATH TO $database; DROP SCHEMA $schema CASCADE;"
+
+  if [ $? -eq 0 ]; then
 		echo -e "${GREEN}Schema $schema has been dropped successfully !${NO_COLOR}"
-	else
+	elseSchema
 		echo -e "${RED}Failed to drop schema $schema !${NO_COLOR}"
 	fi
 	pause
 }
-
 
 menus() {
 	clear
@@ -240,12 +237,13 @@ menus() {
 	echo "4. Drop Postgres User"
 	echo "5. Drop Postgres Database"
 	echo "6. Drop Postgres Schema"
-	echo "7. Exit"
+  echo "7. List all Postgres users"
+	echo "8. Exit"
 }
 
 read_options() {
 	local choice
-	read -p "Enter choice [ 1 - 7] " choice
+	read -p "Enter choice [ 1 - 8] " choice
 	case $choice in
 		1) add_pg_user ;;
 		2) add_pg_database ;;
@@ -253,19 +251,15 @@ read_options() {
 		4) drop_pg_user ;;
 		5) drop_pg_database ;;
 		6) drop_pg_schema ;;
-		7) exit 0 ;;
-		*) echo -e "${RED}Error...${NO_COLOR}" && sleep 2
+    7) list_pg_users ;;
+		8) exit 0 ;;
+		*) echo -e "${RED}Invalid option.Provide only valid option.${NO_COLOR}" && sleep 1
 	esac
 }
 
 pause(){
   read -p "Press [Enter] key to continue..." fackEnterKey
 }
-
-
-# Run as root, of course.
-# checkRoot
-
 
 # ----------------------------------------------
 # Trap CTRL+C, CTRL+Z and quit singles
